import {Search,ArrowUpRight,SlidersHorizontal,Sparkles,ArrowRight,Compass,Bookmark,CheckCheck,AlertCircle,X} from 'lucide-react';
import {platforms,type Platform,type VideoResult} from '../types/video';
import {quickTerms} from '../data/search_terms';
import {PlatformIcon,platformNames} from '../components/platform';
import {EmptyState,SkeletonCards} from '../components/video_card';
export interface SearchPageProps {query:string;setQuery:(q:string)=>void;selected:Platform[];setSelected:(p:Platform[])=>void;duration:boolean;setDuration:(d:boolean)=>void;search:(q:string)=>void;loading:boolean;cancel:()=>void;searched:string;results:VideoResult[];warnings:string[];error:string;configured:boolean|null;renderCard:(v:VideoResult)=>React.ReactNode;savedCount:number;usedCount:number;goSaved:()=>void}
export function SearchPage(p:SearchPageProps){const platformResults=p.results.filter(v=>p.selected.includes(v.platform));const visible=p.duration?platformResults.filter(v=>v.duration_seconds===null||(v.duration_seconds>=30&&v.duration_seconds<=60)).sort((a,b)=>Number(b.duration_seconds!==null)-Number(a.duration_seconds!==null)):platformResults;
return <><div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/> MENOS BÚSQUEDA, MÁS INSPIRACIÓN</div><h1>Encuentra tu próximo video<span>.</span></h1><p>Encuentra escenas para reaccionar: videos originales o con comentario.</p></div><div className="header-mark"><FilmMark/></div></div>
<div className="search-panel"><form className="search-box" onSubmit={e=>{e.preventDefault();p.search(p.query);}}><Search size={22}/><input aria-label="Tema de búsqueda" placeholder="Ej. infidelidad captada, cliente humillado, karma..." value={p.query} maxLength={200} onChange={e=>p.setQuery(e.target.value)}/><kbd>↵</kbd><button className="button primary" disabled={!p.query.trim()||!p.selected.length} type="submit">{p.loading?'Buscando…':p.searched.trim().toLowerCase()===p.query.trim().toLowerCase()?'Buscar otros':'Buscar'}<ArrowRight size={17}/></button></form><div className="quick-search"><span>Búsquedas rápidas</span><div className="chips">{quickTerms.map((term,i)=><button className="chip" key={term} onClick={()=>p.search(term)}>{i===0&&<Sparkles size={12}/>} {term}</button>)}</div></div><div className="search-filters"><div className="platform-filters"><span className="filter-caption"><SlidersHorizontal size={14}/>Plataforma</span><button className={`filter-pill ${p.selected.length===3?'active':''}`} onClick={()=>p.setSelected([...platforms])}>Todas</button>{platforms.map(platform=><button key={platform} className={`filter-pill ${p.selected.includes(platform)&&p.selected.length!==3?'active':''}`} aria-pressed={p.selected.includes(platform)} onClick={()=>p.setSelected(p.selected.includes(platform)?p.selected.filter(v=>v!==platform):[...p.selected,platform])}><PlatformIcon platform={platform}/>{platformNames[platform]}</button>)}</div><label className="duration-filter">Duración<select value={p.duration?'target':'any'} onChange={e=>p.setDuration(e.target.value==='target')}><option value="target">30s – 60s</option><option value="any">Cualquier duración</option></select></label></div>{!p.selected.length&&<p className="filter-note">Selecciona al menos una plataforma para buscar.</p>}</div>
<div className="filter-note">Buscamos escenas concretas: pareja, trabajadores, confrontaciones y gestos de bondad. Incluimos originales y videoreacciones, usando tus creadores de referencia. Abre el original para confirmar el contenido; el texto no permite verificar si una escena es auténtica.</div>{p.configured===false&&!p.error&&<div className="notice"><AlertCircle size={18}/><div><strong>Conecta tu búsqueda</strong><p>Agrega TAVILY_API_KEY en el archivo .env del servidor y reinicia la aplicación. Tus guardados y cuentas ya están listos.</p></div></div>}
{p.searched||p.loading?<section className="results-section"><div className="section-heading"><div><h2>Resultados para “{p.searched}”</h2><p>{p.loading?'Buscando en las plataformas seleccionadas…':`${visible.length} videos encontrados`}</p></div>{p.loading?<button className="button secondary small" onClick={p.cancel}><X size={14}/>Cancelar</button>:<span className="subtle">Ordenados por relevancia</span>}</div>{p.error&&<div className="notice error" role="alert"><AlertCircle size={18}/><div><strong>No pudimos completar la búsqueda</strong><p>{p.error}</p><button className="text-button" onClick={()=>p.search(p.searched)}>Volver a intentar <ArrowRight size={14}/></button></div></div>}{p.warnings.map(w=><div className="warning" key={w}>{w}</div>)}{p.duration&&!p.loading&&visible.length>0&&<p className="filter-note">Priorizamos videos de 30–60s. Los videos sin duración verificable también se incluyen.</p>}{p.loading?<SkeletonCards/>:visible.length?<div className="video-grid">{visible.map(p.renderCard)}</div>:!p.error?<EmptyState title="No encontramos videos con estas consultas." description="Prueba con una escena concreta: “cliente humilla a empleado” o “infidelidad captada en cámara”."><div className="chips">{quickTerms.slice(0,4).map(t=><button className="chip" key={t} onClick={()=>p.search(t)}>{t}</button>)}</div></EmptyState>:null}</section>:<>
<section className="explore-section"><div className="section-heading"><div><h2>Una idea puede ser tu próxima reacción</h2><p>Elige un tema y encuentra una historia que valga la pena contar.</p></div><span className="tiny-badge">EXPLORA</span></div><div className="category-grid">{[{label:'Cuando llega el karma',term:'karma instantáneo',desc:'Esos finales que nadie vio venir.',class:'karma',icon:'↗',tag:'Karma · Justicia'},{label:'Relaciones sin filtro',term:'discusiones de pareja',desc:'Historias que abren la conversación.',class:'relationships',icon:'♡',tag:'Parejas · Infidelidad'},{label:'Un poco de humanidad',term:'actos de bondad',desc:'Pequeños gestos, grandes historias.',class:'kindness',icon:'✧',tag:'Bondad · Superación'}].map(c=><button className={`category-card ${c.class}`} key={c.term} onClick={()=>p.search(c.term)}><div className="category-art"><span className="art-ring"/><span className="art-ring second"/><span className="art-symbol">{c.icon}</span><span className="category-link"><ArrowUpRight size={18}/></span></div><div className="category-copy"><span>{c.tag}</span><h3>{c.label}</h3><p>{c.desc}</p></div></button>)}</div></section>
<section className="workflow-panel"><div><span className="tiny-badge">TU FLUJO, MÁS SIMPLE</span><h2>De la inspiración a la reacción.</h2><p>Encuentra una buena historia. Nosotros te ayudamos a organizarla.</p></div><div className="workflow-steps">{[{Icon:Compass,label:'Encuentra'},{Icon:Bookmark,label:'Guarda'},{Icon:CheckCheck,label:'Reacciona'}].map(({Icon,label},i)=><div className="workflow-step" key={label}><span><Icon size={20}/></span><strong>{label}</strong>{i<2&&<ArrowRight className="step-arrow" size={15}/>}</div>)}</div></section><div className="collection-strip"><div className="collection-icon"><Bookmark size={20}/></div><div><strong>Tu próxima reacción puede estar en tus guardados</strong><p>{p.savedCount} videos guardados · {p.usedCount} utilizados. Todo bajo control.</p></div><button className="text-button" onClick={p.goSaved}>Ver guardados<ArrowRight size={16}/></button></div></>}
<footer className="page-footer"><span><span className="live-dot"/> Solo contenido público. Siempre en su plataforma original.</span><span>ENCUENTRA. GUARDA. CREA.</span></footer></>;
}
function FilmMark(){return <div className="film-mark"><span/><span/><span/></div>;}
