import {useState} from 'react';
import {Heart,ExternalLink,Clock,CheckCheck,Film,Trash2} from 'lucide-react';
import {PlatformIcon,platformNames} from './platform';
import type {VideoResult,SavedVideo,Settings,VideoStatus} from '../types/video';
export function VideoCard({video,saved,onToggle,onUpdate,onDelete,accounts}:{video:VideoResult;saved?:SavedVideo;onToggle:()=>void;onDelete?:()=>void;onUpdate?:(patch:Partial<Pick<SavedVideo,'status'|'used_in'>>)=>void;accounts:Settings['accounts']}){
 const [broken,setBroken]=useState(false);
 return <article className="video-card"><div className={`thumbnail ${video.platform}`}>
 {video.thumbnail_url&&!broken ? <img src={video.thumbnail_url} alt="" loading="lazy" onError={()=>setBroken(true)}/> : <div className="video-placeholder"><PlatformIcon platform={video.platform} size={40}/><span>Contenido original</span><span className="placeholder-text">Revisa el video en {platformNames[video.platform]}</span></div>}
 <span className="platform-badge"><PlatformIcon platform={video.platform}/>{platformNames[video.platform]}</span><button className={`heart ${saved?'is-saved':''}`} onClick={onToggle} title={saved?'Eliminar de guardados':'Guardar video'} aria-label={saved?'Eliminar de guardados':'Guardar video'}><Heart size={18} fill={saved?'currentColor':'none'}/></button>
 </div><div className="card-body">{saved&&<div className={`saved-label ${saved.status}`}><CheckCheck size={13}/>{saved.status==='used'?'Ya utilizado':saved.status==='discarded'?'Descartado':'Guardado'}</div>}<h3>{video.title}</h3><p className="snippet">{video.description||'Abre el contenido original para revisar este video.'}</p><span className="duration"><Clock size={13}/>{video.duration_seconds===null?'Duración no disponible':`${Math.floor(video.duration_seconds/60)}:${String(video.duration_seconds%60).padStart(2,'0')}`}</span><div className="card-domain">{new URL(video.url).hostname}</div><a className="original-url" href={video.url} target="_blank" rel="noopener noreferrer" title={video.url}>{video.url}</a><div className="card-actions"><a className="button small secondary" href={video.url} target="_blank" rel="noopener noreferrer">Abrir video<ExternalLink size={14}/></a><button className={`button small ${onDelete?'danger':saved?'secondary':'primary'}`} onClick={onDelete??onToggle} aria-label={onDelete?`Eliminar ${video.title}`:undefined}>{onDelete?<Trash2 size={14}/>:<Heart size={14}/>} {onDelete?'Eliminar':saved?'Guardado':'Guardar'}</button></div>
 {onUpdate&&saved&&<div className="saved-controls"><label>Estado<select value={saved.status} onChange={e=>onUpdate({status:e.target.value as VideoStatus})}><option value="pending">Pendiente</option><option value="used">Usado</option><option value="discarded">Descartado</option></select></label><fieldset><legend>Usado en</legend>{accounts.map(account=><label className="account-check" key={account.id}><input type="checkbox" checked={saved.used_in.includes(account.id)} onChange={e=>{const used_in=e.target.checked?[...saved.used_in,account.id]:saved.used_in.filter(a=>a!==account.id);onUpdate({used_in,...(e.target.checked?{status:'used' as const}:{})});}}/>{account.name}</label>)}</fieldset></div>}
 </div></article>;
}
export function SkeletonCards(){return <div className="video-grid" aria-label="Buscando videos" aria-busy="true">{Array.from({length:6},(_,i)=><div className="video-card skeleton-card" key={i}><div className="skeleton skeleton-image"/><div className="card-body"><div className="skeleton skeleton-line"/><div className="skeleton skeleton-line short"/><div className="skeleton skeleton-line"/></div></div>)}</div>;}
export function EmptyState({title,description,children}:{title:string;description:string;children?:React.ReactNode}){return <div className="empty-state"><div className="empty-icon"><Film size={27}/></div><h3>{title}</h3><p>{description}</p>{children}</div>;}
